import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import { Spinner } from '@/components/ui/spinner'
import { FileText, Sparkles, Copy, Download } from 'lucide-react'

export function DocsPage() {
  const [code, setCode] = useState('')
  const [documentation, setDocumentation] = useState('')
  const [loading, setLoading] = useState(false)

  const handleGenerate = async () => {
    if (!code.trim()) return
    setLoading(true)
    await new Promise((r) => setTimeout(r, 1500))
    const mockDoc = `# Code Documentation

## Overview
This code snippet contains a function or module that performs specific operations.

## Functions

### Main Function
- **Purpose**: Executes the primary logic
- **Parameters**: Varies based on implementation
- **Returns**: Results of the operation

## Usage Example
\`\`\`javascript
${code.split('\n').slice(0, 3).join('\n')}
\`\`\`

## Notes
- Ensure proper error handling
- Consider edge cases
---
*Generated by Novaryn Documentation Generator*`
    setDocumentation(mockDoc)
    setLoading(false)
  }

  const handleCopy = async () => { await navigator.clipboard.writeText(documentation) }
  const handleDownload = () => {
    const blob = new Blob([documentation], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'documentation.md'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2">
        <FileText className="h-6 w-6 text-primary" />
        <h1 className="text-2xl font-bold">Documentation Generator</h1>
        <Badge variant="secondary">AI Powered</Badge>
      </div>
      <div className="grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Input Code</CardTitle>
            <CardDescription>Paste your code below to generate documentation</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <Textarea placeholder="Paste your code here..." rows={15} value={code} onChange={(e) => setCode(e.target.value)} className="font-mono" />
            <Button onClick={handleGenerate} disabled={loading || !code.trim()} className="w-full">
              {loading ? <><Spinner className="mr-2 h-4 w-4" />Generating...</> : <><Sparkles className="mr-2 h-4 w-4" />Generate Documentation</>}
            </Button>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>Generated Documentation</CardTitle>
                <CardDescription>AI-generated documentation for your code</CardDescription>
              </div>
              {documentation && (
                <div className="flex gap-2">
                  <Button variant="outline" size="icon" onClick={handleCopy}><Copy className="h-4 w-4" /></Button>
                  <Button variant="outline" size="icon" onClick={handleDownload}><Download className="h-4 w-4" /></Button>
                </div>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {documentation ? (
              <div className="prose prose-sm dark:prose-invert max-h-[400px] overflow-auto">
                <pre className="whitespace-pre-wrap rounded-lg bg-muted p-4 text-sm">{documentation}</pre>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-12 text-center text-muted-foreground">
                <FileText className="h-12 w-12 opacity-50" />
                <p className="mt-4">Your generated documentation will appear here</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
